require 'rake'
require 'rake/gempackagetask'

task :default => :spec

# Gemming
#
desc "Create the picky search engine client"
spec = Gem::Specification.new do |s|
  s.name = 'picky-client'
  s.version = '0.0.0'
  s.author = 'Florian Hanke'
  s.email = 'florian.hanke+picky-client@gmail.com'
  s.homepage = 'http://floere.github.com/picky'
  s.platform = Gem::Platform::RUBY
  s.summary = 'picky Search Engine Client'
  s.files = Dir["lib/**/*.rb"]
  s.test_files = Dir["spec/**/*_spec.rb"]
  s.has_rdoc = false
  s.extra_rdoc_files = ['README.textile']
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

require 'spec'
require 'spec/rake/spectask'

spec_root = File.join(File.dirname(__FILE__), 'spec')

desc "Run all specs in spec directory (excluding plugin specs)"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "\"#{File.join(spec_root, 'spec.opts')}\""]
  t.spec_files = FileList[File.join(spec_root, '**', '*_spec.rb')]
end
namespace :spec do

  desc "Run all specs in spec directory with RCov (excluding plugin specs)"
  Spec::Rake::SpecTask.new(:rcov) do |t|
    t.spec_opts = ['--options', "\"spec/spec.opts\""]
    t.spec_files = FileList['spec/**/*_spec.rb']
    t.rcov = true
    t.rcov_opts = lambda do
      IO.readlines("#{SEARCH_ROOT}/spec/rcov.opts").map {|l| l.chomp.split " "}.flatten
    end
  end

  desc "Print Specdoc for all specs (excluding plugin specs)"
  Spec::Rake::SpecTask.new(:doc) do |t|
    t.spec_opts = ["--format", "specdoc", "--dry-run"]
    t.spec_files = FileList['spec/**/*_spec.rb']
  end

end