source :gemcutter

# Gems required by Picky.
#
gem 'rake'
gem 'rack',       '~> 1.3'
gem 'rack-mount', '~> 0.6'
gem 'text',       '~> 0.2'
gem 'yajl-ruby',  '~> 0.7', :require => 'yajl'

# Should be optional, but isn't yet.
#
gem 'activesupport', '~> 3.0', :require => 'active_support/core_ext'
gem 'activerecord',  '~> 3.0', :require => 'active_record'

# Optional.
#
gem 'rack_fast_escape', '2009.06.24'

# Required by your project.
#
gem 'thin'
gem 'mysql'
gem 'sinatra'
gem 'haml'
gem 'redis'

group :test do
  gem 'picky-client'
  gem 'rspec'
end