source 'https://rubygems.org'

# Gems required by the Picky client.
#
gem 'picky-client', '~> 4.0'
gem 'i18n'
gem 'activesupport', :require => 'active_support/core_ext'
gem 'sinatra'
gem 'tilt', '~> 1.4.1'
gem 'haml'

# Gems required by the Picky server.
#
gem 'picky', '~> 4.0'
gem 'rake'
gem 'rack'
gem 'text'
gem 'multi_json'

# Optional.
#
gem 'yajl-ruby', '~> 1.2', :require => 'yajl' # For faster JSON handling
gem 'activerecord', '~> 3', :require => 'active_record' # If you use AR for the DB
gem 'procrastinate', '~> 0.4' # Parallel indexing

# Required by your project.
#
gem 'unicorn'

group :test do
  gem 'rspec'
end