#!/usr/bin/env ruby
#

require File.expand_path '../version', __FILE__

system "gem install bundler"

puts "Installing all gems."
system "cd server; bundle install"
system "cd server/test_project; bundle install"
system "cd server/test_project_sinatra; bundle install"
system "cd client; bundle install"
system "cd statistics; bundle install"
system "cd generators; bundle install"
system "cd live; bundle install"