#!/usr/bin/env ruby
#

require File.expand_path '../version', __FILE__

puts "Installing all gems."
system "cd server; gem build picky.gemspec; gem install picky-*.gem; rm picky-*.gem"
system "cd client; gem build picky-client.gemspec; gem install picky-client-*.gem; rm picky-client-*.gem"
system "cd statistics; gem build picky-statistics.gemspec; gem install picky-statistics-*.gem; rm picky-statistics-*.gem"
system "cd generators; gem build picky-generators.gemspec; gem install picky-generators-*.gem; rm picky-generators-*.gem"