#!/bin/bash

# TODO Completely rewrite all.
#

echo
echo "Don't forget to run"
echo "cd web; bundle exec middleman build; cd .."

# Old picky pages.
#
git branch -D gh-pages
git checkout -b gh-pages             # switch to new gh-pages branch
git checkout master -- web/build     # checkout just the web/build folder from master
cp -r web/build/* .                  # TODO Make elegant
git add .                            # commit the changes
git commit -m "Picky website update" # commit the changes
git push -f origin gh-pages             # 
git checkout master                  # go back to the master branch

# New picky page.
#
cd ../pickyrb.com
cp -r ../picky/web/build/* .
git checkout master
git add .
git commit -m "Picky website update"
git push origin master
cd ../picky