#!/bin/bash
echo
echo "Don't forget to run"
echo "cd web; bundle exec middleman build; cd .."

git checkout gh-pages                # switch to gh-pages branch

git checkout master -- web/build     # checkout just the web/build folder from master
cp -r web/build/* .                  # TODO Make elegant
git add .                            # commit the changes
git commit -m "Picky website update" # commit the changes
git push origin gh-pages             # 

git checkout master                  # go back to the master branch