#!/usr/bin/env ruby
#

require File.expand_path '../version', __FILE__

puts "Releasing with version #{Picky::VERSION}. Ok? (Ctrl-C aborts)"
gets
system "cd server;     gem release"
system "cd client;     gem release"
system "cd generators; gem release"