#!/usr/bin/env ruby
#

require File.expand_path '../version', __FILE__

puts "Running all specs."
system "cd live;       bundle exec rake"
system "cd generators; bundle exec rake"
system "cd statistics; bundle exec rake"
system "cd client;     bundle exec rake"
system "cd server;     bundle exec rake; cd test_project; bundle exec rake"