#!/usr/bin/env ruby
#

require File.expand_path '../version', __FILE__

puts "Running all specs."
system "cd generators; rake"
system "cd statistics; rake"
system "cd client;     rake"
system "cd server;     rake; cd test_project; rake"