source :gemcutter

# Gems required by Picky.
#
gem 'picky', '~> 3.0'
gem 'rake'
gem 'rack'
gem 'rack-mount'
gem 'rack_fast_escape', '2009.06.24' # Optional.
gem 'text'
gem 'yajl-ruby', :require => 'yajl'

# Should be optional, but isn't yet.
#
gem 'activesupport', '~> 3.0', :require => 'active_support/core_ext'
gem 'activerecord',  '~> 3.0', :require => 'active_record'

# Required by your project.
#
gem 'unicorn'
gem 'mysql' # Project specific.
gem 'redis' # Project specific.

group :test do
  gem 'picky-client', '~> 3.0'
  gem 'rspec'
end