source :gemcutter

# Gems required by Picky.
#
gem 'bundler',          '>=0.9.26'
gem 'activerecord',     '2.3.8', :require => 'active_record'
gem 'rack',             '1.2.1'
gem 'rack-mount',       '0.6.9'
gem 'yajl-ruby',                 :require => 'yajl'
gem 'text',             '0.2.0'
gem 'rack_fast_escape', '2009.06.24'

group :test do
  gem 'rspec', '1.3.0'
end