source 'https://rubygems.org'

gemspec

group :development do
  gem 'procrastinate'
  gem 'rack'
  gem 'rake'
  gem 'text'

  # gem 'google_hash'
  gem 'stackprof'
  # gem 'perfer'
  gem 'ffi'
end

group :test do
  gem 'rake-compiler'
  gem 'rspec'
  gem 'rubocop'

  # Needed for testing itself.
  #
  gem 'simplecov', :require => false # Will install simplecov-html as a dependency

  # Needed to test optional data sources etc.
  #
  gem 'activerecord'
  gem 'highline'
  gem 'hiredis'
  gem 'picky-client'
  gem 'redis'
  gem 'rest-client'
  gem 'sinatra'
  gem 'sqlite3'
  gem 'uuidtools'
  gem 'www-delicious'

  gem 'fast-stemmer', :require => 'stemmer'
  gem 'ruby-stemmer', :require => 'lingua/stemmer'

  gem 'ostruct'

  gem 'rack-mount'

  gem 'pippi'
end

group :coverage do
  gem 'coverband'
end
