source 'https://rubygems.org'

ruby '2.2.0'

gemspec

group :development do
  gem 'rake'
  gem 'rack'
  gem 'text'
  gem 'procrastinate'

  gem 'stackprof'
  # gem 'perfer'
end

group :test do
  gem 'rspec', '~> 3.0.0.beta'
  gem 'rake-compiler'

  # Needed for testing itself.
  #
  gem 'simplecov', :require => false # Will install simplecov-html as a dependency

  # Needed to test optional data sources etc.
  #
  gem 'sinatra'
  gem 'www-delicious'
  gem 'rest-client'
  gem 'uuidtools'
  gem 'highline'
  gem 'picky-client'
  gem 'activerecord'
  gem 'hiredis'
  gem 'redis'
  gem 'sqlite3'

  gem 'fast-stemmer', :require => 'stemmer'
  gem 'ruby-stemmer', :require => 'lingua/stemmer'

  gem 'rack-mount'
  
  gem 'pippi'
end

group :coverage do
  gem 'coverband'
end