# require 'rake'
#
# task :default => :rspec
#
# all_rake_files = File.expand_path '../tasks/*.rake', __FILE__
#
# Dir[all_rake_files].each do |rakefile|
#   load rakefile
# end

require File.expand_path '../lib/picky/tasks', __FILE__

require 'rspec'
require 'rspec/core/rake_task'

task :default => :spec

RSpec::Core::RakeTask.new :spec