# This file has been generated by Picky.
#

# Require the gem. This loads the search framework.
#
require ::File.join(::File.dirname(__FILE__), '/../lib/picky')

# Load your application. This requires the files in lib TODO
#
Loader.load_application

# Load the data. This loads data from cache files e.g. "some_index/*_index.dump" into constant Indexes::SomeIndex.
#
Indexes.load_from_cache

# Use Harakiri middleware to kill unicorn child after X requests.
#
# See http://vimeo.com/12614970 for more info.
#
    Rack::Harakiri.after = 1000
use Rack::Harakiri

# Finalize and start the application and start accepting requests.
#
    BookSearch.finalize
run BookSearch