# This file has been generated by Picky.
#

# Require the gem. This loads the search framework.
#
require File.expand_path '../../lib/picky', __FILE__

# Load your application.
#
Loader.load_application

# Load the indexes.
#
Indexes.reload

# Use Harakiri middleware to kill unicorn child after X requests.
#
# See http://vimeo.com/12614970 for more info.
#
#     Rack::Harakiri.after = 1000
# use Rack::Harakiri

# Finalize and start the application and start accepting requests.
#
run BookSearch