source :gemcutter

# Gems required by Picky.
#
gem 'bundler',    '>= 0.9.26'
gem 'rack',       '~> 1.2.1'
gem 'rack-mount', '~> 0.6.9'
gem 'text',       '~> 0.2.0'
gem 'yajl-ruby',  '~> 0.7.8', :require => 'yajl'

# Should be optional, but isn't yet.
#
gem 'activesupport', '~> 3.0', :require => 'active_support/core_ext'
gem 'activerecord',  '~> 3.0', :require => 'active_record'

# Optional.
#
gem 'rack_fast_escape', '2009.06.24'

# Required by your project.
#
gem 'unicorn'
gem 'mysql'
gem 'sinatra'
gem 'haml'
gem 'redis'

group :test do
  gem 'rspec', '~> 1.3.0'
end