source 'http://rubygems.org'

gem 'activesupport'
gem 'multi_json'
gem 'rack'
gem 'rake'
gem 'rspec'
gem 'sinatra'
gem 'text'

# Optional.
#
gem 'activerecord', require: 'active_record' # If you use AR for the DB
gem 'activerecord-postgresql-adapter'
gem 'pg'
gem 'procrastinate', '~> 0.4' # Parallel indexing
gem 'redis'
gem 'sqlite3'
gem 'yajl-ruby', require: 'yajl' # For faster JSON handling
