require File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'picky-tasks'))

require 'spec'
require 'spec/rake/spectask'

task :default => :spec

spec_root = File.join(File.dirname(__FILE__), 'spec')

desc "Run all specs in spec directory (excluding plugin specs)"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "\"#{File.join(spec_root, 'spec.opts')}\""]
  t.spec_files = FileList[File.join(spec_root, '**', '*_spec.rb')]
end