require File.expand_path '../../lib/picky-tasks', __FILE__

require 'spec'
require 'spec/rake/spectask'

task :default => :spec

spec_root = File.join(File.dirname(__FILE__), 'spec')

desc "Run all specs in spec directory."
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "\"#{File.join(spec_root, 'spec.opts')}\""]
  t.spec_files = FileList[File.join(spec_root, '**', '*_spec.rb')]
end