source :gemcutter

# Gems required by Picky.
#
gem 'picky'
gem 'bundler',          '>=0.9.26'
gem 'rack',             '1.2.1'
gem 'rack-mount',       '0.6.9'
gem 'text',             '0.2.0'
gem 'yajl-ruby',        '0.7.8', :require => 'yajl'

# Should be optional.
#
gem 'activesupport',    '2.3.8', :require => 'active_support'
gem 'activerecord',     '2.3.8', :require => 'active_record'

# Optional.
#
gem 'rack_fast_escape', '2009.06.24'

# Required by your project.
#
gem 'unicorn'
gem 'mysql'