source :gemcutter

# Gems required by Picky.
#
gem 'picky',      '3.0.0.pre1'
gem 'rake'
gem 'bundler'
gem 'rack',       '~> 1.2.2'
gem 'rack-mount', '~> 0.6.13'
gem 'text',       '~> 0.2.0'
gem 'yajl-ruby',  '~> 0.8.1', :require => 'yajl'

# Should be optional, but isn't yet. Sorry.
#
gem 'activesupport', '~> 3.0', :require => 'active_support/core_ext'
gem 'activerecord',  '~> 3.0', :require => 'active_record'

# Optional. Makes rack faster.
#
gem 'rack_fast_escape', '2009.06.24'

# Optional. Use your preferred web server.
#
gem 'unicorn'

# Optional. Use your preferred database adapter.
#
gem 'mysql'

# Integration testing needs the client.
#
group :test do
  gem 'picky-client', '3.0.0.pre1'
  gem 'rspec'
end