require 'rake'
require 'rake/gempackagetask' # TODO Remove.

task :default => :spec

# Specs.
#
require 'spec'
require 'spec/rake/spectask'

spec_root = File.join(File.dirname(__FILE__), 'spec')

desc "Run specs"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_opts = ['--options', "\"#{File.join(spec_root, 'spec.opts')}\""]
  t.spec_files = FileList[File.join(spec_root, '**', '*_spec.rb')]
end