source :rubygems

# Gems required by the Picky client.
#
gem 'picky-client', '~> 4.0'
gem 'activesupport', :require => 'active_support/core_ext'
gem 'sinatra'
gem 'haml'

group :development do
  gem 'sinatra-reloader'
  gem 'rake'
end